/*
 * Project name:
     MyProject.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     6/19/2022
 * Test configuration:
     MCU:             STM32F407ZG
     Dev.Board:       Mikromedia_4_for_STM32_Capacitive
     Oscillator:      168000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "MyProject_objects.h"
extern void InitTimer2();
extern void systemInit();
extern void applicationInit();


void main() {

  Start_TP();
  InitTimer2();
  systemInit();
  applicationInit();

  while (1) {
    Check_TP();
  }
}
